class_name WavLoader
extends RefCounted
## Loads a 16-bit PCM RIFF/WAVE file into an `AudioStreamWAV` without relying
## on Godot's asset-import pipeline.
##
## Why this exists: `game/audio/sfx/*.wav` are generated by
## `tools/generate_sfx.gd` at build time, so a freshly cloned checkout (and the
## headless test runner, which never runs the editor importer) may have no
## `.import` sidecar or `.godot/imported/*.sample` for them yet. Parsing the
## RIFF bytes directly makes the audio work in every context.
##
## Everything here is local file I/O. No network, ever.

const _HEADER_MIN_BYTES: int = 44


## Returns an `AudioStreamWAV` for `path`, or `null` if the file is missing or
## is not a mono/stereo 16-bit PCM WAVE. Never pushes an engine error.
static func load_wav(path: String) -> AudioStreamWAV:
	if not FileAccess.file_exists(path):
		return null
	var file: FileAccess = FileAccess.open(path, FileAccess.READ)
	if file == null:
		return null
	var bytes: PackedByteArray = file.get_buffer(file.get_length())
	file.close()
	return parse(bytes)


## Parses raw RIFF bytes. Exposed separately so tests can feed it fixtures.
static func parse(bytes: PackedByteArray) -> AudioStreamWAV:
	if bytes.size() < _HEADER_MIN_BYTES:
		return null
	if bytes.slice(0, 4).get_string_from_ascii() != "RIFF":
		return null
	if bytes.slice(8, 12).get_string_from_ascii() != "WAVE":
		return null

	var channels: int = 0
	var mix_rate: int = 0
	var bits: int = 0
	var audio_format: int = 0
	var pcm: PackedByteArray = PackedByteArray()
	var found_fmt: bool = false
	var found_data: bool = false

	# Walk the chunk list rather than assuming the canonical 44-byte layout, so
	# a file carrying extra chunks (LIST/fact/...) still loads.
	var offset: int = 12
	while offset + 8 <= bytes.size():
		var chunk_id: String = bytes.slice(offset, offset + 4).get_string_from_ascii()
		var chunk_size: int = bytes.decode_u32(offset + 4)
		var body: int = offset + 8
		if chunk_size < 0 or body + chunk_size > bytes.size():
			chunk_size = bytes.size() - body
		if chunk_size < 0:
			break

		if chunk_id == "fmt " and chunk_size >= 16:
			audio_format = bytes.decode_u16(body)
			channels = bytes.decode_u16(body + 2)
			mix_rate = bytes.decode_u32(body + 4)
			bits = bytes.decode_u16(body + 14)
			found_fmt = true
		elif chunk_id == "data":
			pcm = bytes.slice(body, body + chunk_size)
			found_data = true

		# Chunks are word-aligned.
		offset = body + chunk_size + (chunk_size & 1)

	if not found_fmt or not found_data:
		return null
	if audio_format != 1 or bits != 16:
		return null
	if channels < 1 or channels > 2:
		return null
	if mix_rate <= 0 or pcm.is_empty():
		return null

	var stream: AudioStreamWAV = AudioStreamWAV.new()
	stream.format = AudioStreamWAV.FORMAT_16_BITS
	stream.mix_rate = mix_rate
	stream.stereo = channels == 2
	stream.loop_mode = AudioStreamWAV.LOOP_DISABLED
	stream.data = pcm
	return stream
