extends RefCounted
## The music catalogue and the licence gate in front of it.
##
## Music is the only asset class in this project that is not ours: every SFX is
## synthesised by `tools/generate_sfx.gd` and carries no licence surface at all,
## while a music track is generated by a human in Suno and arrives with a
## provenance story attached. `music_manifest.gd` turns that story into data, and
## this case is what stops the data from being decorative.
##
## Three things are asserted here that are worth stating plainly:
##
## 1. **The gate fails closed.** A track plays only when `commercialUse` is
##    exactly `"verified"` AND `licenseEvidence` names something real. "pending",
##    "denied", a bool `true`, a typo, an empty evidence string -- all refused.
##    A rights gate that has to be *understood* to be safe is not a gate.
##
## 2. **A missing file is not an error.** Both tracks are listed in the shipped
##    manifest before they exist; that is the designed state. The loader reports
##    them as absent and the game stays silent, with no engine error anywhere.
##
## 3. **The round-trip loses nothing**, including fields this version of the
##    schema does not know about. A loader that quietly drops a field it does not
##    understand is a loader that loses provenance -- and provenance is the entire
##    reason this file exists.
##
## Fixtures here are dictionaries, never files. This case creates no audio.

const MANIFEST_SCRIPT: String = "res://scripts/audio/music_manifest.gd"
const SHIPPED_MANIFEST: String = "res://content/audio/manifest.json"
## The pre-clearance manifest, kept as a fixture so the silent path stays tested.
const PENDING_FIXTURE: String = "res://tests/fixtures/audio_manifest_pending.json"

## The two tracks Anny is generating. Named here so that renaming one in the
## manifest without telling anyone fails a test rather than silently muting a
## scene.
const EXPECTED_TRACK_IDS: Array[String] = ["littleDaysTheme", "hungryBunny"]

## A file that really is on disk, so a fixture can isolate "refused on licence"
## from "refused because there is nothing to play". It is one of our own
## generated effects: no licence surface, and nothing is added to the repository
## to make this test work.
const REAL_FILE: String = "res://audio/sfx/gentle_tap.wav"

var _script: GDScript = null


func test_name() -> String:
	return "audio_music_manifest"


func run():
	var failures: Array = []

	var loaded: Resource = load(MANIFEST_SCRIPT)
	if loaded == null or not (loaded is GDScript):
		return ["could not load %s" % MANIFEST_SCRIPT]
	_script = loaded as GDScript

	failures.append_array(_test_shipped_manifest_is_well_formed())
	failures.append_array(_test_shipped_manifest_is_cleared())
	failures.append_array(_test_pending_manifest_is_silent())
	failures.append_array(_test_round_trip_loses_nothing())
	failures.append_array(_test_licence_gate_fails_closed())
	failures.append_array(_test_evidence_must_name_something())
	failures.append_array(_test_a_cleared_present_track_is_playable())
	failures.append_array(_test_schema_violations_are_rejected_not_half_loaded())
	failures.append_array(_test_corrupt_and_missing_input())
	failures.append_array(_test_volume_ceiling())
	failures.append_array(_test_loop_points())
	failures.append_array(_test_extension_fallback())

	return failures


# -----------------------------------------------------------------------------
# The manifest that actually ships
# -----------------------------------------------------------------------------


func _test_shipped_manifest_is_well_formed():
	var failures: Array = []

	if not FileAccess.file_exists(SHIPPED_MANIFEST):
		return ["%s is missing; the audio system has no catalogue" % SHIPPED_MANIFEST]

	var manifest: RefCounted = _script.new()
	if not manifest.load_file(SHIPPED_MANIFEST):
		failures.append("load_file() rejected the shipped manifest: %s" % str(manifest.errors()))
		return failures

	var errors: Array = manifest.errors()
	if not errors.is_empty():
		failures.append(
			"the shipped manifest has schema errors, which means a track was dropped or "
			+ "flagged: %s" % str(errors)
		)

	var ids: Array = manifest.track_ids()
	for expected: String in EXPECTED_TRACK_IDS:
		if not ids.has(expected):
			failures.append(
				("the shipped manifest does not list `%s`. Both expected tracks must be listed "
				+ "BEFORE they exist -- that is what makes the delivery a file drop rather than a "
				+ "code change.") % expected
			)

	# Every declared field must be present on every row, or the manifest is not
	# recording provenance -- it is recording an intention to.
	for track_id: String in ids:
		var track: Dictionary = manifest.get_track(track_id)
		for field: String in _script.REQUIRED_FIELDS:
			if not track.has(field):
				failures.append("track %s has no `%s` field" % [track_id, field])

	# A row is a copy, so nobody can mutate the catalogue by holding one.
	if not ids.is_empty():
		var first_id: String = String(ids[0])
		var before: String = String(manifest.get_track(first_id)["commercialUse"])
		var cleared_before: bool = manifest.licence_cleared(first_id)
		var row: Dictionary = manifest.get_track(first_id)
		# Flip whatever it is, so the case bites whether the row is pending or cleared.
		row["commercialUse"] = "denied" if before == _script.COMMERCIAL_USE_VERIFIED \
				else _script.COMMERCIAL_USE_VERIFIED
		row["licenseEvidence"] = "invented by a caller"
		var after: String = String(manifest.get_track(first_id)["commercialUse"])
		if after != before:
			failures.append(
				"mutating the dictionary returned by get_track() changed the catalogue; a caller "
				+ "must not be able to change a track's licence by editing a copy"
			)
		if manifest.licence_cleared(first_id) != cleared_before:
			failures.append("the catalogue changed a licence after a caller edited a copied row")

	return failures


## The shipped state of this repository, as of the 2026-09-19 delivery: two tracks
## listed, **both files now present**, and still nothing playable -- because no
## licence evidence has been supplied for either.
##
## That is the gate doing its job, and it is the assertion that matters most in
## this file. Anny delivered two real tracks; the owner has not said what rights
## come with them. Until someone does, `commercialUse` stays `"pending"`, the gate
## stays shut and the game ships silent. The temptation this case exists to defeat
## is the small edit -- `"pending"` -> `"verified"`, evidence invented -- that
## would make the music audible and the project liable.
## The shipped rows were cleared on 2026-09-20 on the project owner's written
## commercial-use confirmation (tool: Suno; the Suno plan at generation is
## recorded as UNVERIFIED, not invented). The evidence string must therefore name
## a record that really exists in the repository, and both tracks must be
## playable for exactly the scenes the manifest lists. The silent path is still
## proven, against a pending fixture, in `_test_pending_manifest_is_silent()`.
func _test_shipped_manifest_is_cleared():
	var failures: Array = []

	var manifest: RefCounted = _script.new()
	manifest.load_file(SHIPPED_MANIFEST)

	for track_id: String in manifest.track_ids():
		if not manifest.is_playable(track_id):
			failures.append("track %s is refused (%s); the owner cleared both tracks on 2026-09-20"
					% [track_id, manifest.refusal_reason(track_id)])
		var row: Dictionary = manifest.get_track(track_id)
		if String(row.get("commercialUse", "")) != "verified":
			failures.append("track %s commercialUse is %s" % [track_id, str(row.get("commercialUse", ""))])
		# The evidence must point at a record that is really in the repository.
		var evidence: String = String(row.get("licenseEvidence", ""))
		var record: String = evidence.get_slice("Record: ", 1).strip_edges()
		if record.is_empty() or not FileAccess.file_exists("res://../" + record):
			failures.append("track %s: licenseEvidence names no record on disk ('%s')" % [track_id, evidence])
		if not String(row.get("source", "")).contains("Suno"):
			failures.append("track %s: source no longer records the production tool" % track_id)

	if manifest.playable_track_for_scene("menu") != "littleDaysTheme":
		failures.append("menu resolves to '%s', expected littleDaysTheme" % manifest.playable_track_for_scene("menu"))
	if manifest.playable_track_for_scene("miniGame") != "hungryBunny":
		failures.append("miniGame resolves to '%s', expected hungryBunny" % manifest.playable_track_for_scene("miniGame"))
	if manifest.playable_track_for_scene("somethingElse") != "":
		failures.append("an unknown scene resolved to a track")

	if not manifest.missing_track_ids().is_empty():
		failures.append("missing_track_ids() is %s; both files must be on disk" % str(manifest.missing_track_ids()))
	if not manifest.licence_refused_track_ids().is_empty():
		failures.append("licence_refused_track_ids() is %s; expected none" % str(manifest.licence_refused_track_ids()))

	return failures


## The silent path, kept alive for the next unverified delivery: the same two
## real files, with the paperwork still pending, must be refused for the
## paperwork and nothing else.
func _test_pending_manifest_is_silent():
	var failures: Array = []
	var manifest: RefCounted = _script.new()
	if not manifest.load_file(PENDING_FIXTURE):
		return ["could not load %s: %s" % [PENDING_FIXTURE, str(manifest.errors())]]
	for track_id: String in manifest.track_ids():
		if manifest.is_playable(track_id):
			failures.append("pending fixture track %s reports as playable" % track_id)
		if manifest.refusal_reason(track_id) != _script.REFUSAL_COMMERCIAL_USE_UNVERIFIED:
			failures.append("pending fixture track %s refused for '%s', expected commercialUseUnverified"
					% [track_id, manifest.refusal_reason(track_id)])
	for scene: String in ["menu", "house", "miniGame", "reward", "somethingElse"]:
		if manifest.playable_track_for_scene(scene) != "":
			failures.append("pending fixture: scene %s resolved to a playable track" % scene)
	if not manifest.missing_track_ids().is_empty():
		failures.append("pending fixture: files missing %s (the silence must be the paperwork)" % str(manifest.missing_track_ids()))
	if manifest.licence_refused_track_ids().size() != manifest.track_count():
		failures.append("pending fixture: expected every track refused, got %s" % str(manifest.licence_refused_track_ids()))
	return failures


# -----------------------------------------------------------------------------
# Round-trip
# -----------------------------------------------------------------------------


func _test_round_trip_loses_nothing():
	var failures: Array = []

	var manifest: RefCounted = _script.new()
	manifest.load_file(SHIPPED_MANIFEST)
	var first: Dictionary = manifest.to_dictionary()

	# Dictionary -> manifest -> dictionary.
	var second_pass: RefCounted = _script.new()
	second_pass.ingest_dictionary(first)
	var second: Dictionary = second_pass.to_dictionary()
	if str(second) != str(first):
		failures.append(
			"dictionary round-trip changed the manifest:\n  before %s\n  after  %s"
			% [str(first), str(second)]
		)

	# Manifest -> JSON text -> manifest.
	var third_pass: RefCounted = _script.new()
	third_pass.ingest_json(manifest.to_json_string())
	var third: Dictionary = third_pass.to_dictionary()
	if str(third) != str(first):
		failures.append(
			"JSON round-trip changed the manifest:\n  before %s\n  after  %s"
			% [str(first), str(third)]
		)

	# A field this schema version does not know about must survive. The next
	# version of the manifest will add one, and a loader that drops it loses
	# provenance rather than merely being untidy.
	var extended: RefCounted = _script.new()
	extended.ingest_dictionary(
		{
			"manifestVersion": 1,
			"musicDir": "res://audio/music",
			"tracks": [_fixture_track({"stemsArchive": "user://stems/little_days.zip"})],
		}
	)
	var kept: Dictionary = extended.get_track("fixtureTrack")
	if String(kept.get("stemsArchive", "")) != "user://stems/little_days.zip":
		failures.append("an unknown field was dropped by the loader; provenance must survive a load")
	var rebuilt: RefCounted = _script.new()
	rebuilt.ingest_dictionary(extended.to_dictionary())
	if String(rebuilt.get_track("fixtureTrack").get("stemsArchive", "")) != \
			"user://stems/little_days.zip":
		failures.append("an unknown field was dropped by the round-trip")

	return failures


# -----------------------------------------------------------------------------
# The gate
# -----------------------------------------------------------------------------


## The central rule. Everything except an exact `"verified"` is refused, and the
## fixture's file genuinely exists -- so the ONLY thing standing between these
## tracks and playback is the licence.
func _test_licence_gate_fails_closed():
	var failures: Array = []

	if not FileAccess.file_exists(REAL_FILE):
		return ["%s is missing; this case cannot isolate licence refusal from a missing file"
				% REAL_FILE]

	var refused_values: Array = [
		_script.COMMERCIAL_USE_PENDING,
		_script.COMMERCIAL_USE_DENIED,
		"",
		"Verified",   # capitalisation is not a licence
		"verified?",
		"yes",
		true,         # a bool is not evidence of anything
		1,
	]

	for value: Variant in refused_values:
		var manifest: RefCounted = _single_track_manifest(
			{
				"commercialUse": value,
				"licenseEvidence": "docs/licences/fixture.txt",
				"localPath": REAL_FILE,
			}
		)
		if manifest.licence_cleared("fixtureTrack"):
			failures.append(
				("commercialUse %s cleared the licence gate. Only the exact string \"verified\" "
				+ "may. This gate must fail closed: a typo that opens it is indistinguishable "
				+ "from a decision.") % JSON.stringify(value)
			)
		if manifest.is_playable("fixtureTrack"):
			failures.append(
				("a track with commercialUse %s is playable even though its file exists. The "
				+ "audio manager would then play music nobody has cleared for commercial use.")
				% JSON.stringify(value)
			)
		var reason: String = manifest.refusal_reason("fixtureTrack")
		if reason != _script.REFUSAL_COMMERCIAL_USE_UNVERIFIED:
			failures.append(
				"commercialUse %s should be refused with `%s`, got `%s`"
				% [
					JSON.stringify(value),
					_script.REFUSAL_COMMERCIAL_USE_UNVERIFIED,
					reason,
				]
			)
		if not _script.is_licence_refusal(reason):
			failures.append("`%s` should classify as a licence refusal" % reason)

	# An out-of-schema value must also be REPORTED, not silently normalised: a
	# loader that rewrites `true` to "pending" is tidier and erases the evidence
	# that someone typed something wrong.
	var typo: RefCounted = _single_track_manifest({"commercialUse": "yes"})
	if typo.errors().is_empty():
		failures.append("an out-of-schema commercialUse value produced no error")

	# And the licence is checked BEFORE the disk, so a refused track cannot become
	# playable on the day someone happens to drop a file in.
	var no_file: RefCounted = _single_track_manifest(
		{
			"commercialUse": _script.COMMERCIAL_USE_DENIED,
			"licenseEvidence": "docs/licences/fixture.txt",
			"localPath": "res://audio/music/not_here.ogg",
		}
	)
	if no_file.refusal_reason("fixtureTrack") != _script.REFUSAL_COMMERCIAL_USE_UNVERIFIED:
		failures.append(
			"a denied track with no file reported a file problem; the licence must be the "
			+ "reported reason, or the refusal disappears the moment the file arrives"
		)

	# An unknown id is refused too, rather than being a special case somewhere.
	if no_file.refusal_reason("neverHeardOfIt") != _script.REFUSAL_UNKNOWN_TRACK:
		failures.append("an unknown track id must be refused with `unknownTrack`")
	if no_file.is_playable("neverHeardOfIt"):
		failures.append("an unknown track id must never be playable")

	return failures


## `commercialUse: "verified"` with nothing to back it up is not verification.
func _test_evidence_must_name_something():
	var failures: Array = []

	for evidence: String in [
		"", "   ", _script.EVIDENCE_PENDING, "pending", "TODO", "tbd", "none", "n/a", "unknown",
	]:
		var manifest: RefCounted = _single_track_manifest(
			{
				"commercialUse": _script.COMMERCIAL_USE_VERIFIED,
				"licenseEvidence": evidence,
				"localPath": REAL_FILE,
			}
		)
		if manifest.licence_cleared("fixtureTrack"):
			failures.append(
				("licenseEvidence %s cleared the gate. \"verified\" with no evidence behind it is "
				+ "someone's memory, and the point of the manifest is that the rights do not live "
				+ "in anyone's memory.") % JSON.stringify(evidence)
			)
		if manifest.refusal_reason("fixtureTrack") != _script.REFUSAL_LICENCE_EVIDENCE_MISSING:
			failures.append(
				"evidence %s should be refused with `%s`, got `%s`"
				% [
					JSON.stringify(evidence),
					_script.REFUSAL_LICENCE_EVIDENCE_MISSING,
					manifest.refusal_reason("fixtureTrack"),
				]
			)

	return failures


## The positive case, so none of the above is passing for the wrong reason.
func _test_a_cleared_present_track_is_playable():
	var failures: Array = []

	var manifest: RefCounted = _single_track_manifest(
		{
			"commercialUse": _script.COMMERCIAL_USE_VERIFIED,
			"licenseEvidence": "docs/licences/fixture.txt (read from the archive on 2026-09-19)",
			"localPath": REAL_FILE,
			"usageScenes": ["menu", "house"],
		}
	)

	if not manifest.licence_cleared("fixtureTrack"):
		failures.append("a verified track with real evidence must clear the licence gate")
	if not manifest.is_playable("fixtureTrack"):
		failures.append(
			"a verified, evidenced, present track must be playable, got refusal `%s`. Without "
			% manifest.refusal_reason("fixtureTrack")
			+ "this the whole case could be passing by refusing everything."
		)
	if manifest.refusal_reason("fixtureTrack") != _script.REFUSAL_NONE:
		failures.append("a playable track must give no refusal reason")
	if manifest.playable_track_for_scene("menu") != "fixtureTrack":
		failures.append("a playable track must be found by its usage scene")
	if manifest.playable_track_for_scene("bathroom") != "":
		failures.append("a scene the track does not declare must resolve to \"\"")
	if not manifest.licence_refused_track_ids().is_empty():
		failures.append("a cleared track must not appear in licence_refused_track_ids()")
	if not manifest.missing_track_ids().is_empty():
		failures.append("a present file must not be reported as missing")

	# A localPath of "" is its own refusal, distinct from "the file is not there".
	var pathless: RefCounted = _single_track_manifest(
		{
			"commercialUse": _script.COMMERCIAL_USE_VERIFIED,
			"licenseEvidence": "docs/licences/fixture.txt",
			"localPath": "",
		}
	)
	if pathless.refusal_reason("fixtureTrack") != _script.REFUSAL_LOCAL_PATH_MISSING:
		failures.append("a cleared track with no localPath should report `localPathMissing`")

	# The expected everyday case: cleared, evidenced, and simply not delivered yet.
	var absent: RefCounted = _single_track_manifest(
		{
			"commercialUse": _script.COMMERCIAL_USE_VERIFIED,
			"licenseEvidence": "docs/licences/fixture.txt",
			"localPath": "res://audio/music/not_delivered_yet.ogg",
		}
	)
	if absent.refusal_reason("fixtureTrack") != _script.REFUSAL_FILE_MISSING:
		failures.append("a cleared track with no file should report `fileMissing`")
	if _script.is_licence_refusal(_script.REFUSAL_FILE_MISSING):
		failures.append(
			"`fileMissing` must NOT classify as a licence refusal -- it is the expected state of "
			+ "this build, and warning about it would be noise that teaches people to ignore the "
			+ "warning that matters"
		)

	return failures


# -----------------------------------------------------------------------------
# Malformed input
# -----------------------------------------------------------------------------


func _test_schema_violations_are_rejected_not_half_loaded():
	var failures: Array = []

	# A row missing any required field is dropped outright. A track with no
	# `licenseEvidence` key is not a track with pending evidence; it is a track
	# nobody has thought about.
	for field: String in _script.REQUIRED_FIELDS:
		var row: Dictionary = _fixture_track({})
		row.erase(field)
		var manifest: RefCounted = _script.new()
		manifest.ingest_dictionary({"tracks": [row]})
		if manifest.has_track("fixtureTrack"):
			failures.append("a track missing `%s` was loaded anyway" % field)
		if manifest.errors().is_empty():
			failures.append("a track missing `%s` was dropped without an error" % field)

	# An empty trackId cannot be addressed, so it is dropped.
	var empty_id: RefCounted = _script.new()
	empty_id.ingest_dictionary({"tracks": [_fixture_track({"trackId": "   "})]})
	if empty_id.track_count() != 0:
		failures.append("a track with an empty trackId must be dropped")

	# A duplicate id must not silently shadow the first entry.
	var duplicated: RefCounted = _script.new()
	duplicated.ingest_dictionary(
		{
			"tracks": [
				_fixture_track({"volumeDb": -20.0}),
				_fixture_track({"volumeDb": -8.0}),
			],
		}
	)
	if duplicated.track_count() != 1:
		failures.append("a duplicate trackId should leave exactly one entry")
	if not is_equal_approx(float(duplicated.get_track("fixtureTrack")["volumeDb"]), -20.0):
		failures.append("the FIRST entry should win a duplicate trackId, so a later edit cannot "
				+ "quietly override a reviewed row")
	if duplicated.errors().is_empty():
		failures.append("a duplicate trackId should be reported")

	# Wrong types where a type is load-bearing.
	var bad_types: RefCounted = _script.new()
	bad_types.ingest_dictionary(
		{
			"tracks": [
				_fixture_track({"usageScenes": "menu", "volumeDb": "loud"}),
			],
		}
	)
	var row: Dictionary = bad_types.get_track("fixtureTrack")
	if not (row.get("usageScenes") is Array):
		failures.append("a non-array usageScenes must normalise to an array, not stay a String")
	if not (row.get("volumeDb") is float):
		failures.append("a non-numeric volumeDb must normalise to a float")
	if bad_types.errors().size() < 2:
		failures.append("both type violations should be reported, got %s" % str(bad_types.errors()))

	# `tracks` not being an array at all, and a non-object row.
	var not_a_list: RefCounted = _script.new()
	not_a_list.ingest_dictionary({"tracks": "littleDaysTheme"})
	if not_a_list.track_count() != 0 or not_a_list.errors().is_empty():
		failures.append("a non-array `tracks` must load nothing and report it")

	var junk_row: RefCounted = _script.new()
	junk_row.ingest_dictionary({"tracks": ["littleDaysTheme", 7, null]})
	if junk_row.track_count() != 0 or junk_row.errors().size() != 3:
		failures.append("each non-object row should be dropped with its own error")

	return failures


## Missing and corrupt input must produce safe defaults, exactly as the save
## layer does. `CLAUDE.md` requires it of the profile; audio is no different.
func _test_corrupt_and_missing_input():
	var failures: Array = []

	var missing: RefCounted = _script.new()
	if missing.load_file("res://content/audio/no_such_manifest.json"):
		failures.append("load_file() should return false for a path that does not exist")
	if not missing.is_empty():
		failures.append("a missing manifest must produce an empty catalogue")
	if missing.errors().is_empty():
		failures.append("a missing manifest must record why it is empty")
	# And an empty catalogue must answer every question without erroring.
	if missing.is_playable("littleDaysTheme") or missing.licence_cleared("littleDaysTheme"):
		failures.append("an empty catalogue must refuse everything")
	if missing.playable_track_for_scene("menu") != "":
		failures.append("an empty catalogue must resolve every scene to \"\"")
	if not missing.resolved_path("littleDaysTheme").is_empty():
		failures.append("an empty catalogue must resolve no paths")
	if not is_equal_approx(missing.volume_db_for("littleDaysTheme"), _script.FALLBACK_VOLUME_DB):
		failures.append(
			"an unknown track's level must fall back to the quiet default, not to 0 dB; a "
			+ "fallback that is louder than the design is the wrong direction to fail in"
		)

	for corrupt: String in ["", "   ", "not json at all", "[1,2,3]", "{", "null", "\"a string\""]:
		var manifest: RefCounted = _script.new()
		if manifest.ingest_json(corrupt):
			failures.append("ingest_json(%s) should return false" % JSON.stringify(corrupt))
		if not manifest.is_empty():
			failures.append("corrupt JSON %s produced tracks" % JSON.stringify(corrupt))
		if manifest.errors().is_empty():
			failures.append("corrupt JSON %s was accepted silently" % JSON.stringify(corrupt))

	# Loading twice must not accumulate: a reload replaces, it does not append.
	var reloaded: RefCounted = _script.new()
	reloaded.load_file(SHIPPED_MANIFEST)
	var count: int = reloaded.track_count()
	reloaded.load_file(SHIPPED_MANIFEST)
	if reloaded.track_count() != count:
		failures.append("reloading the manifest doubled the catalogue")
	# ...and a failed reload leaves an empty, safe catalogue rather than stale rows.
	reloaded.load_file("res://content/audio/no_such_manifest.json")
	if not reloaded.is_empty():
		failures.append("a failed reload must leave a safe empty catalogue, not stale tracks")

	return failures


# -----------------------------------------------------------------------------
# Playback parameters
# -----------------------------------------------------------------------------


## Music plays UNDER the English the child is meant to hear. The ceiling is a
## child-UX decision, not a mixing preference, so no manifest entry may exceed it.
func _test_volume_ceiling():
	var failures: Array = []

	if _script.MAX_VOLUME_DB >= 0.0:
		failures.append(
			"MAX_VOLUME_DB is %.1f. Music must sit below the level of a spoken prompt."
			% _script.MAX_VOLUME_DB
		)

	for requested: float in [0.0, 6.0, 120.0, -6.0]:
		var manifest: RefCounted = _single_track_manifest({"volumeDb": requested})
		var actual: float = manifest.volume_db_for("fixtureTrack")
		if actual > _script.MAX_VOLUME_DB:
			failures.append(
				"a manifest asking for %.1f dB produced %.1f dB, above the %.1f dB ceiling"
				% [requested, actual, _script.MAX_VOLUME_DB]
			)

	var quiet: RefCounted = _single_track_manifest({"volumeDb": -500.0})
	if quiet.volume_db_for("fixtureTrack") < _script.MIN_VOLUME_DB:
		failures.append("an absurdly low volumeDb must clamp to MIN_VOLUME_DB")

	# The shipped entries must already respect the ceiling as written, so nobody
	# relies on the clamp to save them.
	var shipped: RefCounted = _script.new()
	shipped.load_file(SHIPPED_MANIFEST)
	for track_id: String in shipped.track_ids():
		var declared: float = float(shipped.get_track(track_id).get("volumeDb", 0.0))
		if declared > _script.MAX_VOLUME_DB:
			failures.append(
				"shipped track %s declares %.1f dB, above the ceiling" % [track_id, declared]
			)

	return failures


func _test_loop_points():
	var failures: Array = []

	var normal: RefCounted = _single_track_manifest({"loopStart": 1.5, "loopEnd": 32.0})
	var points: Dictionary = normal.loop_points("fixtureTrack")
	if not is_equal_approx(float(points["loopStart"]), 1.5):
		failures.append("loopStart was not preserved")
	if not is_equal_approx(float(points["loopEnd"]), 32.0):
		failures.append("loopEnd was not preserved")

	# A loop that ends before it starts is no loop at all; it must degrade to
	# "loop the whole file" rather than producing a zero-length loop that would
	# buzz on a device.
	var inverted: RefCounted = _single_track_manifest({"loopStart": 8.0, "loopEnd": 2.0})
	if not is_zero_approx(float(inverted.loop_points("fixtureTrack")["loopEnd"])):
		failures.append("an inverted loop range must fall back to the whole file")

	var negative: RefCounted = _single_track_manifest({"loopStart": -4.0, "loopEnd": -1.0})
	var safe: Dictionary = negative.loop_points("fixtureTrack")
	if float(safe["loopStart"]) < 0.0 or float(safe["loopEnd"]) < 0.0:
		failures.append("negative loop points must clamp to 0")

	var unknown: Dictionary = negative.loop_points("neverHeardOfIt")
	if not is_zero_approx(float(unknown["loopStart"])) \
			or not is_zero_approx(float(unknown["loopEnd"])):
		failures.append("an unknown track must yield zeroed loop points, not an error")

	return failures


## Suno exports MP3; we would rather ship OGG. A delivery must not be defeated by
## which of those Anny happened to have, so a declared `.ogg` resolves to a
## sibling file with an accepted extension.
func _test_extension_fallback():
	var failures: Array = []

	var manifest: RefCounted = _single_track_manifest(
		{
			"commercialUse": _script.COMMERCIAL_USE_VERIFIED,
			"licenseEvidence": "docs/licences/fixture.txt",
			"localPath": "res://audio/sfx/gentle_tap.ogg",
		}
	)
	var resolved: String = manifest.resolved_path("fixtureTrack")
	if resolved != REAL_FILE:
		failures.append(
			("a declared .ogg should resolve to the delivered %s, got `%s`. Without this a "
			+ "correct delivery in the wrong container is silently no music at all.")
			% [REAL_FILE, resolved]
		)
	if not manifest.is_playable("fixtureTrack"):
		failures.append("a track resolved by extension fallback must be playable")

	# The fallback must not invent files: an unknown basename stays unresolved.
	var nothing: RefCounted = _single_track_manifest(
		{
			"commercialUse": _script.COMMERCIAL_USE_VERIFIED,
			"licenseEvidence": "docs/licences/fixture.txt",
			"localPath": "res://audio/sfx/no_such_effect.ogg",
		}
	)
	if not nothing.resolved_path("fixtureTrack").is_empty():
		failures.append("the extension fallback must not resolve a basename that does not exist")

	return failures


# -----------------------------------------------------------------------------
# Fixtures
# -----------------------------------------------------------------------------


## A complete, schema-valid row. `overrides` replaces individual fields, so each
## assertion above varies exactly one thing.
func _fixture_track(overrides: Dictionary) -> Dictionary:
	var row: Dictionary = {
		"trackId": "fixtureTrack",
		"source": "test fixture (no file is created by this case)",
		"createdAt": "2026-09-19",
		"downloadedAt": "",
		"licenseEvidence": _script.EVIDENCE_PENDING,
		"commercialUse": _script.COMMERCIAL_USE_PENDING,
		"localPath": "res://audio/music/fixture.ogg",
		"loopStart": 0.0,
		"loopEnd": 0.0,
		"volumeDb": -14.0,
		"usageScenes": ["menu"],
	}
	for key: Variant in overrides.keys():
		row[String(key)] = overrides[key]
	return row


func _single_track_manifest(overrides: Dictionary) -> RefCounted:
	var manifest: RefCounted = _script.new()
	manifest.ingest_dictionary(
		{
			"manifestVersion": 1,
			"musicDir": "res://audio/music",
			"tracks": [_fixture_track(overrides)],
		}
	)
	return manifest
